enableImmutableInstalls: false

npmPublishAccess: public

npmRegistries:
  //registry.npmjs.org:
    npmAuthToken: ''

packageExtensions:
  css@*:
    dependencies:
      fs: '*'
  debug@*:
    dependencies:
      supports-color: '*'
  # see https://github.com/mielientiev/testcontainers-dynamodb/issues/1
  testcontainers-dynamodb@*:
    dependencies:
      testcontainers: '*'
  webpack@*:
    peerDependencies:
      webpack-cli: '*'
    peerDependenciesMeta:
      webpack-cli:
        optional: true

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'

yarnPath: .yarn/releases/yarn-3.0.2.cjs
