compressionLevel: mixed

enableGlobalCache: false

enableImmutableInstalls: false

npmPublishAccess: public

npmRegistries:
  //registry.npmjs.org:
    npmAuthToken: ""

packageExtensions:
  "@swc-node/sourcemap-support@*":
    dependencies:
      tslib: "*"
  css@*:
    dependencies:
      fs: "*"
  debug@*:
    dependencies:
      supports-color: "*"
  express@*:
    dependencies:
      ejs: "*"

yarnPath: .yarn/releases/yarn-4.0.2.cjs
