name: Template Deployment for DEV

on: [push]

jobs:
  build:
    name: 'Deploy build set'
    strategy:
      fail-fast: false
      matrix:
        deploy-set:
          [
            'backend-go-gin',
            'backend-lambda-api',
            'backend-nodejs-express',
            'nextjs',
            'nextjs-bootstrap',
            'no-infra',
            'email-send',
            's3',
            'static-website',
            'user-management',
            'dynamodb',
            'server-side-rendering',
          ]
    if: "contains(github.event.head_commit.message, 'trigger_template_deploy_dev') && github.ref == 'refs/heads/master'"
    runs-on: ubuntu-latest
    steps:
      - name: Collect Workflow Telemetry
        uses: runforesight/foresight-workflow-kit-action@v1
        if: ${{ always() }}
        with:
          api_key: ${{secrets.FORESIGHT_API_KEY}}
      - name: Checkout Goldstack repo
        uses: actions/checkout@25a956c84d5dd820d28caab9f86b8d183aeeff3d
        with:
          fetch-depth: 20
          token: ${{secrets.BUILD_TOKEN}}
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
          registry-url: https://registry.npmjs.org
      - name: Install Yarn
        run: npm install -g yarn@1.22.11
      - name: Install project dependencies
        run: |
          yarn install
      - name: Run build set
        run: |
          cd workspaces/apps/packages/template-management-cli
          yarn cli deploy-set \
            --set ${{ matrix.deploy-set }} \
            --deployment dev \
            --repo goldstack-dev \
            --workDir /tmp/set/ \
            --emailResultsTo false
        env:
          AWS_USER_NAME: goldstack-dev
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_DEFAULT_REGION: us-west-2
          GITHUB_TOKEN: ${{secrets.BUILD_TOKEN}}
